 pipeline {
    agent any

 
 	stages {
 	
        stage('SCM Checkout') {
            steps {
                git "https://github.com/TanumayDhar/DevopsTest1.git"
                
                
            }
        }
        stage('Build') {
            steps {
             
                
       			echo 'Building the application...'
                
                
            }
        }
        stage('Integration Test') {
            steps {
            
            	script{
                bat (/mvn clean test/)
                }
                echo 'Deploying in server...'
            }
        }
    }
}
 
 