 pipeline {
    agent any

 
 	stages {
 	
        stage('SCM Checkout') {
            steps {
                git "https://github.com/TanumayDhar/DevopsTest1/tree/master/DevopsSelenium"
            }
        }
        stage('Build') {
            steps {
             
                
       			echo 'Building the application...'
                
                
            }
        }
        stage('Integration Test') {
            steps {
                echo 'Deploying in server...'
            }
        }
    }
}
 