 pipeline {
    agent any

 

    stages {
        stage('Build') {
            steps {
                echo 'Building..the application for checking Poll SCM scn 2'
            }
        }
        stage('Test') {
            steps {
             
             
             
                echo 'Testing.the application.'
                
                
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying in server...'
            }
        }
    }
}
 